feat: added checkbox component
BoraRachar/borarachar.web pull request #26
Opened 2023-07-12 16:02 UTC by DorvilleThiago

2023-07-12 22:55 UTC, devalyssonchiarelly requested changes
Olá Thiago tudo bem? solicito que seja feita uma alteração. Na linha 24 quando você define as classes do tailwind, no final você utilizar o border-black para aplicar a cor a borda do input do tipo checkbox, a classe 'border-black' do tailwind equivale a cor '#000000'. Essa não é a cor que foi definida pelo time de UX/UI para ser utilizada na borda do checkbox.

Já temos definidas as cores que serão utilizadas no projeto, no arquivo tailwind.config.js, então recomendo a troca da classe 'border-black' pela classe 'border-neutral-black', está última classe equivale a cor '#232324', cor que foi definida pelo time de UX/UI.

2023-07-13 11:39 UTC, filipexxborba requested changes
No aguardo da alteração solicitado pelo Alysson

2023-07-13 14:40 UTC, devalyssonchiarelly approved these changes

2023-07-13 16:21 UTC, filipexxborba approved these changes
Approved

2023-07-13 18:48 UTC, merged